version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v3.10.0
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: volume
        source: prometheus_data
        target: /prometheus
    configs:
      - source: prometheus_config
        target: /prometheus.yml
    command:
      - '--config.file=/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - monitoring
    ports:
      - "9090:9090"
    healthcheck:
      test: [ "CMD", "wget",  "-q", "--spider", "http://localhost:9090" ]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 40s
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
        reservations:
          cpus: "0.25"
          memory: 512M

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    command:
      - "--store_container_labels=true"
      - "--docker_only=true"
    volumes:
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /sys
        target: /sys
        read_only: true
      - type: bind
        source: /var/lib/docker/
        target: /var/lib/docker
        read_only: true
    networks:
      - monitoring
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M

  node-exporter:
    image: prom/node-exporter:v1.9.0
    hostname: "{{.Node.Hostname}}"
    volumes:
      - type: bind
        source: /sys
        target: /host/sys
        read_only: true
      - type: bind
        source: /proc
        target: /host/proc
        read_only: true
      - type: bind
        source: /
        target: /rootfs
        read_only: true
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    networks:
      - monitoring
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:9100/metrics" ]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 40s
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
        reservations:
          cpus: "0.1"
          memory: 32M

networks:
  monitoring:
    external: true
    name: monitoring

volumes:
  prometheus_data:

configs:
  prometheus_config:
    file: ./prometheus.yml
